db:
  url: jdbc:mysql://localhost:3306/movieland
  username: root
  password: mirus
  maxIdle: 8
  minIdle: 4
  maxTotal: 12
  initialSize: 3

movie:
  random:
    limit: 3

genre:
  clean:
    cron:
      expression: 0 0 0/4 * * *

currency:
  update:
    cron:
      expression: 0 0 8 * * *
  nbu:
    url: https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange?json